import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Christopher',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Kartik',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [
      {
        name: 'Sea Anemone',
        category: 'Shirts',
        image: '/images/SeaAnemone.jpeg',
        price: 50,
        countInStock: 10,
        brand: 'Hot Topic',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Metallica Ride the lightning',
        category: 'Shirts',
        image: '/images/lightning_metallica.jpeg',
        price: 50,
        countInStock: 20,
        brand: 'Metallica',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Nirvana',
        category: 'Shirts',
        image: '/images/nirvana.jpeg',
        price: 30,
        countInStock: 0,
        brand: 'Nirvana',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        name: 'The Beatles',
        category: 'Shirts',
        image: '/images/beatles.jpeg',
        price: 40,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'American Eagle Blue Jeans',
        category: 'Pants',
        image: '/images/jeans.jpeg',
        price: 160,
        countInStock: 15,
        brand: 'American Eagle',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        name: 'American Eagle Black Jeans',
        category: 'Pants',
        image: '/images/jeans3.jpeg',
        price: 150,
        countInStock: 5,
        brand: 'American Eagle',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'American Eagle Dark Blue Jeans',
        category: 'Pants',
        image: '/images/jeans2.jpeg',
        price: 140,
        countInStock: 12,
        brand: 'American Eagle',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        name: 'AE AirFlex+ Slim Bootcut Jean',
        category: 'Pants',
        image: '/images/jeans4.jpeg',
        price: 160,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;